### ISSUE TITLE
Test is invisible in Test Explorer If TestCaseSource method may return an empty array

### ISSUE THREAD

**Issue by tjozsef** [MilkovD/nunit-runner-vscode-ext#4]
**Expected result:**
Test is visible in the Test Explorer, even if the TestCaseSource method may return an empty array.

**Actual result:**
Test is invisible in the test Explorer if the TestCaseSource method may return an empty array.

**Steps to reproduce:**
1. Clone: https://github.com/tjozsef/Test-Explorer-Bug-Report
2. Open in VS Code
3. Run in the terminal the following command: "dotnet build"
4. Open the Test Explorer

![test_explorer_missing_test](https://github.com/MDcod/nunit-runner-vscode-ext/assets/22714488/3d0716d0-91c3-470a-93d9-c2fa54e8d5f6)

Versions:
NUnit Test Runnerv 0.3.0
----------------------------
VS Code
Version: 1.90.0 (user setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

-----------------------------------------------------------------------------------------------------
Note: Opening the same project in Visual Studio the same Test is visible in the Test Explorer. 
Visual Studio version:

Microsoft Visual Studio Community 2022
Version 17.10.1
Visual Studio.17.Release/17.10.1+34928.147
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

C# Tools   4.10.0-3.24270.2+e8f775c1d8a73dee7ad02408712d714251e708ea

![visual_studio_test_explorer](https://github.com/MDcod/nunit-runner-vscode-ext/assets/22714488/6551ba07-b3d0-420f-8192-af3f965c549b)

**Comment by MilkovD** [comment]
@tjozsef I'm very sorry for the long response. Thank you very much for the detailed bug report.
Bug fixed in version [0.3.1](https://marketplace.visualstudio.com/items?itemName=Forms.nunit-test-runner)
